WebApp/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WebApp.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

WebApp/Models/SvnDirectoryModels.cs
using SharpSvn;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Configuration;

namespace WebApp.Models
{
    public sealed class SvnDirectoryType
    {
        private readonly int _value;
        private readonly string _name;
        private readonly string _className;

        public static readonly SvnDirectoryType Dev = new SvnDirectoryType(1, "Development", "danger");
        public static readonly SvnDirectoryType Stable = new SvnDirectoryType(2, "Stable", "success");
        public static readonly SvnDirectoryType Old = new SvnDirectoryType(3, "Old", "warning");
        public static readonly SvnDirectoryType Project = new SvnDirectoryType(4, "Project", "default");
        public static readonly SvnDirectoryType Unknown = new SvnDirectoryType(5, "Unknown", "info");

        private SvnDirectoryType(int value, string name, string className)
        {
            this._value = value;
            this._name = name;
            this._className = className;
        }

        public override string ToString()
        {
            return _name;
        }
    }

    public class SvnDirectory
    {
        private string _name = string.Empty;
        private SvnDirectoryType _type = null;
        private Configuration _webConfig = null;

        public string Name
        {
            get { return _name; }
            set
            {
                _name = value;
                _webConfig = WebConfigurationManager.OpenWebConfiguration("/" + _name);
            }
        }

        public SvnDirectoryType Type
        {
            get
            {
                if (_type == null)
                {
                    int version = 0;
                    string[] nameSplited = Name.Split('_');
                    foreach (string part in nameSplited)
                    {
                        if (int.TryParse(part, out version))
                            break;
                    }

                    if (!Name.StartsWith("buyer_demo", StringComparison.InvariantCultureIgnoreCase))
                        _type = SvnDirectoryType.Project;
                    else if (!Name.StartsWith("buyer_demo_V8", StringComparison.InvariantCultureIgnoreCase))
                        _type = SvnDirectoryType.Old;
                    else if (version != 0 && (version % 2) == 0)
                        _type = SvnDirectoryType.Stable;
                    else if (version != 0 && (version % 2) != 0)
                        _type = SvnDirectoryType.Dev;
                    else if (Name.StartsWith("buyer_demo_V8_dev", StringComparison.InvariantCultureIgnoreCase))
                        _type = SvnDirectoryType.Dev;
                    else if (Name.StartsWith("buyer_demo_V8", StringComparison.InvariantCultureIgnoreCase))
                        _type = SvnDirectoryType.Stable;
                    else
                        _type = SvnDirectoryType.Unknown;
                }

                return _type;
            }
        }

        public bool HasWebConfig
        {
            get { return _webConfig != null ? _webConfig.HasFile : false; }
        }
        public string Database
        {
            get { return GetConnectionStringData("database"); }
        }
        public string SqlServer
        {
            get { return GetConnectionStringData("server"); }
        }

        public List<string> ListFiles { get; set; } = new List<string>();


        public SvnDirectory() {}

        public string GetConnectionStringData(string property)
        {
            if (HasWebConfig)
            {
                string propertyValue = string.Empty;

                Match matchProperty = Regex.Match(_webConfig.ConnectionStrings.ConnectionStrings["Main"].ConnectionString,
                    string.Format("(\\b{0}(\\s+)?=(\\s+)?\\S+\\;)", property), RegexOptions.IgnoreCase);
                if (matchProperty.Success)
                {
                    propertyValue = matchProperty.Value;

                    int propertyEqualIndex = propertyValue.IndexOf("=") + 1;
                    if (propertyEqualIndex != -1)
                        propertyValue = propertyValue.Substring(propertyEqualIndex, propertyValue.Length - propertyEqualIndex);

                    propertyValue = propertyValue.Trim(new char[] { ' ', '\"', ';' });
                }

                return propertyValue;
            }

            return string.Empty;
        }

        public void GetSvnFiles()
        {
            using (SvnClient svnClient = new SvnClient())
            {
                //var location = new Uri("http://my.example/repos/trunk");
                //svnClient.DiffSummary(
                //    new SvnUriTarget(location, 12),
                //    new SvnUriTarget(location, SvnRevision.Head),
                //    delegate (object sender, SvnDiffSummaryEventArgs e)
                //    {
                //        ListFiles.Add(e.Path);
                //    }
                //);
            }
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

WebApp/Controllers/SvnDirectoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class DirectoryController : Controller
    {
        public ActionResult Dev(SvnDirectoryType type)
        {
            ViewBag.Title = "Dev";
            
            return PartialView("List", GetSvnDirectories(type));
        }

        public ActionResult Stable(SvnDirectoryType type)
        {
            ViewBag.Title = "Stable";

            return PartialView("List", GetSvnDirectories(type));
        }

        public ActionResult Old(SvnDirectoryType type)
        {
            ViewBag.Title = "Old";

            return PartialView("List", GetSvnDirectories(type));
        }

        public ActionResult Project(SvnDirectoryType type)
        {
            ViewBag.Title = "Project";

            return PartialView("List", GetSvnDirectories(type));
        }

        public ActionResult Edit(SvnDirectory svnDirectory)
        {
            ViewBag.Title = "Edit";

            return PartialView(svnDirectory);
        }

        protected List<SvnDirectory> GetSvnDirectories(SvnDirectoryType type)
        {
            List<SvnDirectory> listSvnDirectories = new List<SvnDirectory>();

            string physicalPath = Server.MapPath("/");
            string[] directories = Directory.GetDirectories(physicalPath, "buyer*");

            foreach (string directory in directories)
            {
                DirectoryInfo di = new DirectoryInfo(directory);
                SvnDirectory svnDirectory = new SvnDirectory()
                {
                    Name = di.Name
                };

                if (svnDirectory.Type == type)
                    listSvnDirectories.Add(svnDirectory);
            }

            return listSvnDirectories;
        }
    }
}

WebApp/Views/Directory/Edit.cshtml
<div class="ui basic segment">
    @if (!string.IsNullOrEmpty(Model.Name))
    {
        <div class="ui fluid card">
            <div class="content">
                <div class="header">@Model.Name</div>
                <div class="meta">@Model.Type</div>
                <div class="description"></div>
            </div>
            @if (Model.HasWebConfig)
            {
                <div class="content">
                    <h4 class="ui sub header">Web.Config</h4>
                    <div class="ui list">
                        <div class="item">
                            <div class="ui black horizontal label">SQL Server</div>
                            @Model.SqlServer
                        </div>
                        <div class="item">
                            <div class="ui blue horizontal label">Database</div>
                            @Model.Database
                        </div>
                    </div>
                </div>
            }
            @if (Model.ListFiles.Count > 0)
            {
                <div class="content">
                    <h4 class="ui sub header">Files</h4>
                </div>
                <div class="ui list">
                    @foreach (string file in Model.ListFiles)
                    {
                        <div class="item">
                            @file
                        </div>
                    }
                </div>
            }
            @*<div class="content">
                <h4 class="ui sub header">Actions</h4>
            </div>*@
        </div>
    }
</div>

WebApp/Views/Directory/List.cshtml
@if (@Model.Count > 0)
{
    <section class="ui basic segment">
        <h2 class="ui header">
            @*<i class="icon"></i>*@
            <div class="content">@ViewBag.Title</div>
        </h2>
        <div class="ui middle align list">
            @foreach (var item in @Model)
            {
                <div class="item" data-name="@item.Name">
                    <i class="edit icon svn-directory-button"></i>
                    <div class="content">
                        @if (item.HasWebConfig)
                        {
                            <a href="@item.Name">@item.Name</a>
                        }
                        else
                        {
                            @item.Name
                        }
                    </div>
                </div>
            }
        </div>
    </section>
}

WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="ui grid">
    <div class="ten wide column">
        @Html.Action("Dev", "Directory", new { type = WebApp.Models.SvnDirectoryType.Dev })
        @Html.Action("Stable", "Directory", new { type = WebApp.Models.SvnDirectoryType.Stable })
        @Html.Action("Old", "Directory", new { type = WebApp.Models.SvnDirectoryType.Old })
        @Html.Action("Project", "Directory", new { type = WebApp.Models.SvnDirectoryType.Project })
    </div>
    <div id="svn-directory-info" class="six wide column">
        @Html.Action("Edit", "Directory")
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="ui top fixed large inverted menu" id="main-nav">
        <div class="ui container">
            <div class="header item">
                @Html.ActionLink("TMO - Localhost", "Index", "Home")
            </div>
        </div>
    </nav>
    <div id="main-content" class="ui container">
        @RenderBody()
    </div>
    @*<footer class="ui black inverted segment">
    </footer>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/semantic")
    @Scripts.Render("~/Scripts/WebApp")
    @RenderSection("scripts", required: false)
</body>
</html>